### ISSUE TITLE
Extraneous formatting and exception when using ExplicitReturnTypes

### ISSUE THREAD

**Issue by fwbrasil** [scalacenter/scalafix#222] opened 2017-06-21 21:02 UTC
## Problem

When running the `ExplicitReturnTypes` rewrite, scalafix formats unrelated code and fails with an exception.

## Steps to reproduce

I've tried to reproduce the problem in isolation but haven't had success. I hope it's fine to report the issue based on the scalding code base (the build takes some time to run). Steps:

```
git clone git@github.com:twitter/scalding.git
cd scalding
git checkout 73c2e694bf235c398aaf61f879ceefa1fbd4f944
echo 'addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.4.2")' >> project/plugins.sbt
sbt scalafix ExplicitReturnTypes
```

Note that this file was formatted: 

```
 git diff scalding-hadoop-test/src/test/scala/com/twitter/scalding/reducer_estimation/ReducerEstimatorTest.scala

diff --git a/scalding-hadoop-test/src/test/scala/com/twitter/scalding/reducer_estimation/ReducerEstimatorTest.scala b/scalding-hadoop-test/src/test/scala/com/twitter/scalding/reducer_estimation/ReducerEstimatorTest.scala
index 6b07958..e6238dd 100644
--- a/scalding-hadoop-test/src/test/scala/com/twitter/scalding/reducer_estimation/ReducerEstimatorTest.scala
+++ b/scalding-hadoop-test/src/test/scala/com/twitter/scalding/reducer_estimation/ReducerEstimatorTest.scala
@@ -88,8 +88,7 @@ class SimpleMemoryJob(args: Args, customConfig: Config) extends Job(args) {

   val inSrc = IterableSource(List(
     "Direct trade American Apparel squid umami tote bag. Lo-fi XOXO gluten-free meh literally, typewriter readymade wolf salvia whatever drinking vinegar organic. Four loko literally bicycle rights drinking vinegar Cosby sweater hella stumptown. Dreamcatcher iPhone 90's organic chambray cardigan, wolf fixie gluten-free Brooklyn four loko. Mumblecore ennui twee, 8-bit food truck sustainable tote bag Williamsburg mixtape biodiesel. Semiotics Helvetica put a bird on it, roof party fashion axe organic post-ironic readymade Wes Anderson Pinterest keffiyeh. Craft beer meggings sartorial, butcher Marfa kitsch art party mustache Brooklyn vinyl.",
-    "Wolf flannel before they sold out vinyl, selfies four loko Bushwick Banksy Odd Future. Chillwave banh mi iPhone, Truffaut shabby chic craft beer keytar DIY. Scenester selvage deep v YOLO paleo blog photo booth fap. Sustainable wolf mixtape small batch skateboard, pop-up brunch asymmetrical seitan butcher Thundercats disrupt twee Etsy. You probably haven't heard of them freegan skateboard before they sold out, mlkshk pour-over Echo Park keytar retro farm-to-table. Tattooed sustainable beard, Helvetica Wes Anderson pickled vinyl yr pop-up Vice. Wolf bespoke lomo photo booth ethnic cliche."
-  ))
+    "Wolf flannel before they sold out vinyl, selfies four loko Bushwick Banksy Odd Future. Chillwave banh mi iPhone, Truffaut shabby chic craft beer keytar DIY. Scenester selvage deep v YOLO paleo blog photo booth fap. Sustainable wolf mixtape small batch skateboard, pop-up brunch asymmetrical seitan butcher Thundercats disrupt twee Etsy. You probably haven't heard of them freegan skateboard before they sold out, mlkshk pour-over Echo Park keytar retro farm-to-table. Tattooed sustainable beard, Helvetica Wes Anderson pickled vinyl yr pop-up Vice. Wolf bespoke lomo photo booth ethnic cliche."))

   override def config = super.config ++ customConfig.toMap.toMap

@@ -241,8 +240,9 @@ class ReducerEstimatorTest extends WordSpec with Matchers with HadoopSharedPlatf
         (Config.ReducerEstimatorOverride -> "true")

       HadoopPlatformJobTest(new SimpleFileNotFoundJob(_, customConfig), cluster)
-        .runExpectFailure { case error: FlowException =>
-          error.getCause.getClass should be(classOf[FileNotFoundException])
+        .runExpectFailure {
+          case error: FlowException =>
+            error.getCause.getClass should be(classOf[FileNotFoundException])
         }
     }
   }
```

And that the command failed with:

```
[info] Running scalafix --no-sys-exit -i --sourceroot /Users/fbrasil/workspace/scalding --classpath /Users/fbrasil/workspace/scalding/scalding-parquet-scrooge/target/scala-2.11/test-classes:/Users/fbrasil/workspace/scalding/scalding-parquet-scrooge/target/scala-2.11/classes
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (scalding-core/compile:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] Total time: 633 s, completed Jun 21, 2017 1:55:27 PM
```

There's also this exception, but I'm not sure if it's a problem:

```
[info] Running scalafix --no-sys-exit -i --sourceroot /Users/fbrasil/workspace/scalding --classpath /Users/fbrasil/workspace/scalding/scalding-core/target/scala-2.11/test-classes:/Users/fbrasil/workspace/scalding/scalding-core/target/scala-2.11/classes
java.lang.RuntimeException: bad protobuf: unsupported name range {
  start: 925
  end: 932
}
symbol: "<none>"
```

**Comment by fwbrasil** [comment] 2017-06-21 21:07
Just verified that the problem isn't specific to `ExplicitReturnTypes`, the other rewrites have the same behavior.

**Comment by olafurpg** [comment] 2017-06-22 08:43
Thank you for reporting! I think the formatting changes are caused by scalariform, which runs on compile. Notice that the diffs appear before the `scalafix --classpath ...` task runs. 

I was able to reproduce the "bad protobuf" error. It appears to be a bug in the scalahost compiler plugin, I am trying to find a minimal repro.

**Comment by olafurpg** [comment] 2017-06-22 09:12
I am also able to reproduce the InvalidCommandLineOption=8 error, scalafix should not report an error in those cases because there were no .scala files to fix. I opened #223 to track that one.

**Comment by olafurpg** [comment] 2017-06-22 09:58
I tracked down the bad protobuf error to a local symbol with Position.None that should not be persisted to the semanticdb. I'm closing this issue in favor of https://github.com/scalameta/scalameta/issues/959 (bad protobuf) and #223 (invalid cli option).

**Closed by olafurpg** 2017-06-22 09:58 UTC

**Comment by fwbrasil** [comment] 2017-06-22 16:02
@olafurpg thanks for the quick feedback and analysis!
