### ISSUE TITLE
ignore generated (expanded macros) code

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#604] opened 2018-02-13 10:24 UTC
#559

**Comment by olafurpg** [comment] 2018-02-13 15:33
Can you include an obtained/expected example? By design, the Disable rule currently disables usage of symbols in both synthetic (macro/implicit/inference) and non-synthetic code. Adding a mode that disables a symbol in non-synthetic code only should be easy to accommodate, and I think https://github.com/scalacenter/scalafix/pull/601 already does most of that work

**Comment by fommil** [comment] 2018-02-13 15:50
a self contained example is tough because it would mean having a compiler plugin or macro... imagine a macro that expands some code to use `.asInstanceOf` and that's a banned symbol. We want to allow this, because we assume it is safe (we'd ban the macro method itself if we thought it was not).

**Comment by olafurpg** [comment] 2018-02-13 16:49
it doesn't have to be a self-contained example. Can you include a printout of scalafix from an example where you encountered this? I suspect the culprit is a synthetic from implicit arguments that are generated by a macro.

**Comment by fommil** [comment] 2018-02-13 17:16
in https://gitlab.com/fommil/drone-dynamic-agents/ uncomment the Disable rule for `scala.Any.asInstanceOf` in `project/scalafix.conf` and do an `sbt lint`, you will see hundreds and hundreds of lines of output like

```
src/main/scala/interpreters/gcefs2.scala:81:6: error: [Disable.asInstanceOf] asInstanceOf is disabled and it got inferred as `*(io.circe.Decoder.importedDecoder[Cluster](new io.circe.export.Exported(((shapeless.lazily.apply[DerivedDecoder[Cluster]]({
  val inst$macro$347: DerivedDecoder[Cluster] = {
    final class anon$exportDecoder$macro$346 extends _root_.scala.Serializable {
      lazy val inst$macro$172: ReprDecoder[HNil] = io.circe.generic.decoding.ReprDecoder.hnilReprDecoder.asInstanceOf[ReprDecoder[HNil]];
      lazy val inst$macro$169: DerivedDecoder[STOPPING.type] = io.circe.generic.decoding.DerivedDecoder.deriveDecoder[STOPPING.type, hnilZipWithKeys.Out](shapeless.LabelledGeneric.materializeProduct[STOPPING.type, HNil, HNil, hnilZipWithKeys.Out]((({

...
```

**Comment by vovapolu** [comment] 2018-02-13 17:22
That's definitely will be fixed by https://github.com/scalacenter/scalafix/pull/601 and `unlessSynthetic` flag

**Comment by vovapolu** [comment] 2018-02-13 17:23
Or not... :)

**Closed** 2018-02-13 17:58 UTC
Labels: bug, sponsored
