### ISSUE TITLE
scalafix configuration should support exclude

### ISSUE THREAD

**Issue by Mharlin** [scalacenter/scalafix#621] opened 2018-02-21 06:00 UTC
The same way you can use ```scalafixCli --exclude <pattern>``` it should be possible to add that exclude pattern into the configuration file. The main reason for asking for this is to be able to exclude files or classes for the sementic rules where it doesn't work with comments in the code.

**Comment by olafurpg** [comment] 2018-02-21 07:38
Thanks for reporting! 

> The main reason for asking for this is to be able to exclude files or classes for the sementic rules where it doesn't work with comments in the code.

Have you opened a ticket for that? I agree it is a good to to support exclude filters in the configuration file, but we should also fix that issue!

**Comment by Mharlin** [comment] 2018-02-21 09:42
Good point Olaf, I will create an issue for that as well.

**Comment by olafurpg** [comment] 2018-05-30 17:06
Seems like a duplicate of #498

**Closed by olafurpg** 2018-05-30 17:06 UTC

**Comment by kmontemayor2-sc** [comment] 2024-11-07 22:24
Hey is this expected to work when running `sbt scalafixAll`?

If I have the following directory structure:

```
.
└── common/
    ├── protos/
    │   ├── foo/
    │   │   └── Foo.scala
    │   └── bar/
    │       └── Bar.scala
    └── utils/
        └── Time.scala
```

Setting up my `.scalafix.conf` as follows does not filter out the generated proto files, when running `sbt scalalfixAll`

```
project.excludePaths = [
    "glob:**/protos/**.scala",
]

```

Also interestingly there seems to be some cached results that `sbt clean` mess with.

```bash
git restore .
sbt clean scalafixAll # formats the proto files
git restore .
sbt scalafixAll # Does not format
```

I also updated my `scalacOptions` with `"-P:semanticdb:exclude:.*proto/.*.scala"` which is also not seemingly taking effect.
