### ISSUE TITLE
Regression in 0.6.0-M7 vs 0.6.0-M5-37-988d7ac2-SNAPSHOT

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#744] opened 2018-06-01 08:58 UTC
This project https://gitlab.com/fommil/drone-dynamic-agents when upgrading to M7, and running `sbt scalafix` gives the following error. It is not clear which rule is causing the problem

```
scalafix.v1.MissingSymbolException: Missing symbol fommil.http.encoding.UrlEncodedWriter#
	at scalafix.v1.SemanticDoc.$anonfun$info$2(SemanticDoc.scala:62)
	at scala.Option.getOrElse(Option.scala:121)
	at scalafix.v1.SemanticDoc.info(SemanticDoc.scala:62)
	at scalafix.internal.patch.DocSemanticdbIndex.denotation(DocSemanticdbIndex.scala:81)
	at scalafix.internal.patch.DocSemanticdbIndex.$anonfun$denotation$1(DocSemanticdbIndex.scala:86)
...
```

**Comment by olafurpg** [comment] 2018-06-19 17:58
Thanks for reporting! I've thought a lot what might be causing this and I believe the problem is https://github.com/scalameta/scalameta/issues/1528 I will work on that ticket tomorrow so this should hopefully be addressed this week.

**Comment by olafurpg** [comment] 2018-06-20 17:48
The PR https://github.com/scalameta/scalameta/pull/1611 has been merged fixing the issue I had enountered with with incremental compilation. The PR added nice testing infrastructure so we can more easily reproduce similar zinc integration issues in the future. I'm gonna close this ticket in favor of #749.

**Closed by olafurpg** 2018-06-20 17:48 UTC
Labels: blocked

**Comment by olafurpg** [comment] 2018-06-20 17:50
PS. The cause for "Missing symbol fommil.http.encoding.UrlEncodedWriter#" can be something other else than incremental compilation. For example, if you use macro annotations you will hit on the same error due to https://github.com/scalameta/scalameta/issues/1504. I will be tackling that issue soon.
