### ISSUE TITLE
RemoveUnused failed cause `failed to generate semanticdb`

### ISSUE THREAD

**Issue by YuJoe** [scalacenter/scalafix#1071] opened 2020-03-13 03:41 UTC
```
[error] failed to generate semanticdb for .../XXX.scala:
[error] java.lang.ArrayIndexOutOfBoundsException: -1
[error] 	at scala.meta.internal.semanticdb.scalac.DiagnosticOps$XtensionCompilationUnitDiagnostics$$anonfun$reportedDiagnostics$1.apply(DiagnosticOps.scala:21)
[error] 	at scala.meta.internal.semanticdb.scalac.DiagnosticOps$XtensionCompilationUnitDiagnostics$$anonfun$reportedDiagnostics$1.apply(DiagnosticOps.scala:11)
[error] 	at scala.collection.immutable.List.map(List.scala:288)
[error] 	at scala.meta.internal.semanticdb.scalac.DiagnosticOps$XtensionCompilationUnitDiagnostics.reportedDiagnostics(DiagnosticOps.scala:11)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:721)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.saveSemanticdbForCompilationUnit(SemanticdbPipeline.scala:60)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:67)
[error] 	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
[error] 	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
[error] 	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
[error] 	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
[error] 	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[error] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:425)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.run(SemanticdbPipeline.scala:77)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
[error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
[error] 	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
[error] 	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
[error] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
[error] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
[error] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
[error] 	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
[error] 	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
[error] 	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
[error] 	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
[error] 	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
[error] 	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
[error] 	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
[error] 	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
[error] 	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
[error] 	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
[error] 	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
[error] 	at sbt.inc.Incremental$.compile(Incremental.scala:71)
[error] 	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
[error] 	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
[error] 	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
[error] 	at sbt.Compiler$.compile(Compiler.scala:155)
[error] 	at sbt.Compiler$.compile(Compiler.scala:141)
[error] 	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:927)
[error] 	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:918)
[error] 	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:916)
[error] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[error] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[error] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error] 	at sbt.Execute.work(Execute.scala:237)
[error] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bjaglin** [comment] 2020-06-01 16:00
Thanks for the report! This looks like a problem in the [SemanticDB scala compiler plugin](https://scalameta.org/docs/semanticdb/guide.html#scalac-compiler-plugin), before scalafix even gets a chance to run.

Could you provide more information about your setup so we could try to reproduce it? Depending on that, it might be better to follow-up in https://github.com/scalameta/scalameta.

**Comment by bjaglin** [comment] 2024-02-05 08:06
Closing as there is no repro so this is not actionnable (and probably outdated).

**Closed by bjaglin** 2024-02-05 08:06 UTC
