### ISSUE TITLE
ExplicitReturnTypes rewrite invalid pattern in type ascription

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#309] opened 2017-08-22 06:17 UTC
Before

```scala
implicit val materializer_ = ActorMaterializer()
```

After

```scala
implicit val materializer_: akka.stream.ActorMaterializer = ActorMaterializer()
```

This is a syntax error.

```scala
 val foo_: Int = 1
<console>:1: error: illegal start of simple pattern
val foo_: Int = 1
              ^

scala> val foo_ : Int = 1
foo_: Int = 1
```

the `_` and the `:` must be separated by a space

**Comment by olafurpg** [comment] 2017-08-22 06:27
Duplicate of #305

**Comment by MasseGuillaume** [comment] 2017-08-22 06:31
@olafurpg You should add the `foo_ ` in the test.

**Comment by olafurpg** [comment] 2017-08-22 06:38
You are totally right! Good catch.

The implementation was borrowed from ScalaIDE so I assumed it handles all corner cases, https://github.com/scala-ide/scala-ide/blob/d8edb1939ab06cb536d54e442d0e23d78070d58a/org.scala-ide.sdt.core/src/org/scalaide/core/internal/quickassist/explicit/ExplicitReturnType.scala#L51

I will fix this quickly.

**Closed** 2017-08-22 08:01 UTC
