### ISSUE TITLE
not support sbt 1.x + scala 2.11.12 + sbt-scalafix 0.9.13

### ISSUE THREAD

**Issue by ericxsun** [scalacenter/scalafix#1091] opened 2020-04-14 02:27 UTC
In repo: https://repo1.maven.org/maven2/ch/epfl/scala/, only the following versions are deployed

- sbt-scalafix_2.10_0.13/  
- sbt-scalafix_2.12_1.0/     

but in our project, we need sbt-scalafix_2.11 while version of sbt is 1.x

Our settings:
```
addSbtPlugin("ch.epfl.scala" %% "sbt-scalafix" % "0.9.13")
addCompilerPlugin("org.scalameta" % "semanticdb-scalac_2.11.12" % "4.3.8")

// sbt 1.x
```

when run `sbt project_name/scalafix`, error occurs as the follow

```
error: Type mismatch;
  found    : Map[K, V] (value: {"scalaVersion": "2.11.12"})
  expected : scalaVersion=2.12.11
[error] (project_name / Compile / scalafix) scalafix.sbt.ScalafixFailed: CommandLineError
```

**Comment by olafurpg** [comment] 2020-04-14 08:35
Thank you for reporting! The ExplicitResultTypes rewrite only supports 2.12.11, not 2.11.12. See https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html#limited-scala-support

I admit the error message could be clearer

**Comment by olafurpg** [comment] 2020-04-14 10:55
Updated the error message to be clearer in #1093 . Closing with "working as intended" since the `ExplicitResultTypes` rule doesn't support 2.11

**Closed by olafurpg** 2020-04-14 10:55 UTC
