### ISSUE TITLE
0.6.0-M11 broken with pants build tool

### ISSUE THREAD

**Issue by ShaneDelmore** [scalacenter/scalafix#769] opened 2018-07-10 23:47 UTC
In testing scalafix 0.6.0-M11 and semanticdb 4.0-M4 I have run into problems with paths.

Using twitter util-core as an example project:
in SBT semanticdbs would be placed in:
  META-INF/semanticdb/relative_path_from_build_target_root

while in pants the same compilation would produce semanticdbs in:
  META-INF/util/util-core/semanticdb/relative_path_from_build_target_root
edit, this was a mistake on my part but I am leaving the original comment to prevent a confusing comment history.  The actual path has the extra directories following semanticdb, not preceeding it as in:
  META-INF/semanticdb/util/util-core/relative_path_from_build_target_root

Currently I don't know of a way to insert this extra path information between the META-INF directory and the semanticdb directory, which breaks both scalafix-cli and scalafix-testkit.

I'm not sure of the best solution, maybe something like a BUILD_TARGET_OFFSET parameter that could be inserted between the META-INF and semanticdb directories would work.

**Comment by olafurpg** [comment] 2018-07-10 23:55
Thanks for reporting! How come the semanticdb directory is not directly underneath the META-INF directory? I've never seen that convention used before. Did this work before on v0.5?

**Comment by olafurpg** [comment] 2018-07-10 23:57
The cli has a flag for the sourceroot that determines the relative directory path after META-INF/semanticdb. Adding an option to control the prefix of semanticdb/ is possible, but I'd like to understand the use case first.

**Comment by ShaneDelmore** [comment] 2018-07-11 00:01
Shoot, my mistake, here is an example path

.pants.d/compile/zinc/current/util.util-core.src.main.scala.scala/current/classes/META-INF/semanticdb/util/util-core/src/main/scala/com/twitter/util/Activity.scala.semanticdb  

for file: https://github.com/twitter/util/blob/develop/util-core/src/main/scala/com/twitter/util/Activity.scala

**Comment by ShaneDelmore** [comment] 2018-07-11 00:04
In 0.5 this just worked.  I did have to make slight changes to scalafix-testkit to override test discovery to make it work.  Due to path fetching code being private in the latest scalafix-testkit I ended up just having to override the whole implementation in https://github.com/scalacenter/scalafix/blob/master/scalafix-testkit/src/main/scala/scalafix/testkit/RuleTest.scala

But didn't want to contribute changes upstream as I am not certain if this is a pants only requirement or if it would impact any non-sbt build tool.

**Comment by olafurpg** [comment] 2018-07-11 16:28
- What is the exact error or problem that you encounter in the pants integration?
- Could it be that --sourceroot is not configured correctly?
- Are you using scalafix-testkit from pants? There were breaking changes that are handled for sbt builds by the migration rewrites here https://github.com/scalacenter/scalafix.g8/tree/master/scalafix

There have been breaking changes since v0.5 how scalafix-cli works. I haven't gotten around to document the migration path yet because things are still in flux, for example current master supports --metacp-cache-dir but that option can go away after we upgrade to https://github.com/scalameta/scalameta/pull/1682.

Most critical difference from before is that --classpath must include the full classpath (including transitive dependencies) when before the --classpath only needed entries for sources that needed to be fixed (no transitive dependencies). From the new --help section

```

Semantic options:

  --classpath Classpath (default: "")
    Full classpath of the files to fix, required for semantic rules. The source
    files that should be fixed must be compiled with semanticdb-scalac.
    Dependencies are required by rules like ExplicitResultTypes, but the
    dependencies do not need to be compiled with semanticdb-scalac.

  --sourceroot <path> (default: null)
    Absolute path passed to semanticdb with -P:semanticdb:sourceroot:<path>.
    Relative filenames persisted in the Semantic DB are absolutized by the
    sourceroot. Defaults to current working directory if not provided.

```

**Comment by ShaneDelmore** [comment] 2018-07-11 18:45
I'm looking into sourceroot, although not sure how I would use that with TestKit.  In the latest TestKit the constructor parameters supplying configuration are replaced by a config file in resources with three parameters which I have filled with:

    inputSourceDirectories=scalafix-rules/input
    outputSourceDirectories=scalafix-rules/output
    inputClasspath=.pants.d/compile/zinc/current/scalafix-rules.input.src.main.scala.scala/current/classes

Does this need an option for sourceroot?
I'll also need to dynamically update this file I guess to update classpath whenever someone adds a new build dependency to the input project now.  

The current errors I get with the default test-kit implementation are:
1.  It tries to parse pants BUILD files (instead of parsing only scala files)
2.  src/main/scala/com/twitter/scalafix/test/sources/Template.scala(main.scala.com.twitter.scalafix.tests.All_Tests)
scalafix.v1.SemanticDoc$Error$MissingSemanticdb: No SemanticDB associated with src/main/scala/com/twitter/scalafix/test/sources/Template.scala

**Comment by olafurpg** [comment] 2018-07-11 23:09
It seems `TestkitProperties` uses `inputSourceDirectories` as the sourceroot for each provided directory. Do you need a different sourceroot than the input directory?

> It tries to parse pants BUILD files (instead of parsing only scala files)

Do you pass it `BUILD` files explicitly? It uses the glob `**.{scala,sbt}` to filter files and that doesn't seem to match `BUILD` so I don't know what's going on
```scala
@ import java.nio.file._
@   val baseMatcher: PathMatcher =
      FileSystems.getDefault.getPathMatcher("glob:**.{scala,sbt}")
baseMatcher: PathMatcher = sun.nio.fs.UnixFileSystem$3@5b9396d3
@ baseMatcher.matches(Paths.get("BUILD"))
res2: Boolean = false
```

> src/main/scala/com/twitter/scalafix/test/sources/Template.scala(main.scala.com.twitter.scalafix.tests.All_Tests)
scalafix.v1.SemanticDoc$Error$MissingSemanticdb: No SemanticDB associated with src/main/scala/com/twitter/scalafix/test/sources/Template.scala

Is this when running in testkit or scalafix-cli? If it's the cli, then have you tried setting --sourceroot?

**Comment by ShaneDelmore** [comment] 2018-07-12 01:21
In case it helps demonstrate the issue more clearly than my explanations I have pushed a PR that fixes scalafix-testkit usage (but breaks SBT usage).

I can spend more time tomorrow to find a solution that works for both tools.  I haven't looked into cli usage yet other than to see that pants is passing sourceroot in correctly both when creating semanticdbs, and when running scalafix-cli.

https://github.com/scalacenter/scalafix/pull/770

**Comment by olafurpg** [comment] 2018-07-12 10:38
Thanks for opening #770 That cleared a lot, I left some questions.

I wasn't aware testkit was used in pants so I haven't been diligent in documenting the breaking changes there 😅

**Comment by ShaneDelmore** [comment] 2018-07-12 23:40
The scalafix-cli issue ended up being due to the most recent version of pants using jarred classpath files, it wasn't actually related to the version bump.  I have pushed a commit to #770 to allow loading semanticdbs from a jarred classpath to resolve the issue.

**Comment by ShaneDelmore** [comment] 2018-07-12 23:42
> I wasn't aware testkit was used in pants

TestKit is used in our internal code as well as tutorials/classes on Scalafix.  We think it's pretty wonderful.

**Comment by olafurpg** [comment] 2018-07-13 15:38
#770 fixes both the sourceroot problem in testkit and adds support for jar entries in --classpath. Let me know if that fixes the regressions in the pants integration!

**Comment by olafurpg** [comment] 2018-07-31 11:50
Can you confirm the regression has been fixed now @ShaneDelmore ?

**Comment by ShaneDelmore** [comment] 2018-08-02 16:06
Yes, works great 👍

**Comment by olafurpg** [comment] 2018-08-02 17:06
Thanks!

**Closed by olafurpg** 2018-08-02 17:06 UTC
