### ISSUE TITLE
Does not work on CrossProject

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#308] opened 2017-08-22 06:03 UTC
I ran sbt-scalafix (0.5.0-M6) on scastie (https://github.com/scalacenter/scastie/commit/290ea049f67a697fba25c11456a4d3786ccdb763).

I got a `java.io.FileNotFoundException` from a `CrossType.Pure` project.

```
java.io.FileNotFoundException: /home/gui/scastie/.cross/api/.js/target/scala-2.12/classes/META-INF/semanticdb/.cross/api/.js (Is a directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.scalajs.core.tools.io.FileVirtualTextFile$.readFileToString(FileVirtualFiles.scala:69)
        at org.scalajs.core.tools.io.FileVirtualTextFile.content(FileVirtualFiles.scala:58)
        at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$perConfigSettings$11$$anonfun$1$$anonfun$apply$6.apply(ScalaJSBundlerPlugin.scala:562)
        at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$perConfigSettings$11$$anonfun$1$$anonfun$apply$6.apply(ScalaJSBundlerPlugin.scala:561)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$perConfigSettings$11$$anonfun$1.apply(ScalaJSBundlerPlugin.scala:561)
        at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$perConfigSettings$11$$anonfun$1.apply(ScalaJSBundlerPlugin.scala:554)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
        at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$perConfigSettings$11.apply(ScalaJSBundlerPlugin.scala:567)
        at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$perConfigSettings$11.apply(ScalaJSBundlerPlugin.scala:544)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I also got several othe error, I'm not sure if they are related:

```
scalafix.cli.Cli$NonZeroExitCode: Got exit code StaleSemanticDB=32
scalafix.cli.Cli$NonZeroExitCode: Got exit code ParseError=2
scalafix.cli.Cli$NonZeroExitCode: Got exit code StaleSemanticDB=32
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
scalafix.cli.Cli$NonZeroExitCode: Got exit code StaleSemanticDB=32
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
java.io.FileNotFoundException: /home/gui/scastie/.cross/api/.js/target/scala-2.12/classes/META-INF/semanticdb/.cross/api/.js (Is a directory)
// stack above
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
scalafix.cli.Cli$NonZeroExitCode: Got exit code StaleSemanticDB=32
[error] (api-2-11-11JS/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code StaleSemanticDB=32
[error] (client/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code ParseError=2
[error] (apiJVM/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code StaleSemanticDB=32
[error] (runtime-scala-2-10-6JS/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (runtime-scala-2-13-0-M1JS/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (sbtScastie/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (api-2-13-0-M1JVM/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (api-2-13-0-M1JS/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (apiJS/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code StaleSemanticDB=32
[error] (runtime-scala-2-10-6JVM/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (runtime-scala-2-13-0-M1JVM/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (client/compile:npmUpdate) java.io.FileNotFoundException: /home/gui/scastie/.cross/api/.js/target/scala-2.12/classes/META-INF/semanticdb/.cross/api/.js (Is a directory)
[error] (api-2-10-6JVM/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (api-2-10-6JS/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (api-2-11-11JVM/*:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code StaleSemanticDB=32
[error] Total time: 158 s, completed Aug 22, 2017 7:56:36 AM
```

**Comment by olafurpg** [comment] 2017-08-22 06:34
It seems the bug origins at

> at org.scalajs.core.tools.io.FileVirtualTextFile$.readFileToString(FileVirtualFiles.scala:69)

and not scalafix. My guess is that the Scala.js compiler is trying to read the `.js` directory created by the semanticdb-scalac compiler plugin (previously scalahost).

The "StaleSemanticDB" errors/warnings are likely caused by the fact that there are two projects (js/jvm) that point to the same source files. Scalafix has guards to not overwrite files that have gone off-sync with their corresponding .semanticdb files (due to being already fixed by the sister js/jvm project). Any ideas how to prevent this from sbt-scalafix? One userland alternative is to override the `scalafix` task to do nothing in the js project.

**Comment by MasseGuillaume** [comment] 2017-08-22 06:39
Hehe it's complicated indeed. I guess one solution would be to add the project to the position. But then you would need to merge rewrites. I guess in practice both projects have the same semantic. Maybe run scalafix on both projects and if they give the same rewrite succeed otherwise fail and tell the user what part they should split.

**Comment by olafurpg** [comment] 2017-08-22 07:06
>  I guess one solution would be to add the project to the position

Can you elaborate?

> Maybe run scalafix on both projects and if they give the same rewrite succeed otherwise fail and tell the user what part they should split.

That is an interesting idea. If the file is stale, then we can check if the contents of the file match the fixed output and return OK=0 instead of StaleSemanticDB=32. Is the following claim valid?

```
It's OK if the semanticdbs are different for js/jvm as long as the scalafix output is the same.
```

>  I guess in practice both projects have the same semantic. 

That is likely the most common case, esp. for CrossType.Pure projects. However, it's quite easy to construct examples where the same name for example resolves to different symbols on js/jvm, so I don't want to not assume it to be so.

**Comment by MasseGuillaume** [comment] 2017-12-18 13:44
@olafurpg Hey, what is the plan for this issue. It seems that multiple things are going wrong.

**Comment by MasseGuillaume** [comment] 2017-12-18 14:06
Splitted into two tickets: https://github.com/scalacenter/scalafix/issues/512

**Comment by olafurpg** [comment] 2018-05-30 17:00
This is a Scala.js bug that should be reported to scala-js/scala-js.

**Comment by olafurpg** [comment] 2018-05-30 17:01
And if we are to workaround the issue on our side, the fix would need to happen in scalameta/scalameta. Either way, it's not a scalafix issue.

**Closed by olafurpg** 2018-05-30 17:00 UTC
