### ISSUE TITLE
ExplicitReturnTypes with unsafeShortenNames is adding current file class as import

### ISSUE THREAD

**Issue by diego-alvarez-hs** [scalacenter/scalafix#329] opened 2017-09-06 18:45 UTC
feel free to rewrite the issue description.

having this configuration:
```
rewrites = [ExplicitReturnTypes, ExplicitUnit, NoAutoTupling, RemoveUnusedImports, ProcedureSyntax] # No rewrites are run if empty.
explicitReturnTypes.unsafeShortenNames = true
```

before running `scalafix` file was like:
```scala
package com.hootsuite.xxx.yyy.models

import play.api.libs.json.Json

case class LinkPreview(
  xxx: Option[String]
)

object LinkPreview {
  implicit val format = Json.format[LinkPreview]
}
```

and now it added the right imports and did a great! job adding the short names, but it added an unnecessary import (same class)

```scala
package com.hootsuite.xxx.yyy.models

import play.api.libs.json.Json

import com.hootsuite.xxx.yyy.models.LinkPreview
import play.api.libs.json.OFormat

case class LinkPreview(
  xxx: Option[String]
)

object LinkPreview {
  implicit val format: OFormat[LinkPreview] = Json.format[LinkPreview]
}
```

**Comment by diego-alvarez-hs** [comment] 2017-09-06 18:49
I think this might be related to https://github.com/scalameta/scalameta/issues/1075

**Comment by olafurpg** [comment] 2017-09-06 18:51
Thank you for reporting! There are a lot of low hanging fruits in unsafeShortenNames :) I have some WIP changes to emulate at least what names are introduced into the scope. It won't handle stuff like wildcard imports or names introduced into scope by super classes, but it will definitely handle stuff like this!

**Comment by olafurpg** [comment] 2017-09-06 18:57
Those issues are indeed related. The reason I haven't included my WIP changes is because I think there is a better way. I want to try and pretty print the types inside the compiler using the `Scope` of the compiler. We did some related work in january https://github.com/scalacenter/scalafix/pull/42 that never got merged.

**Comment by diego-alvarez-hs** [comment] 2017-09-06 22:36
thanks for your amazing job @olafurpg

**Comment by olafurpg** [comment] 2018-08-28 14:48
Duplicate of #502. This is not fixed and I can't give an ETA when it will be but the API in the next release will be able to implement this functionality. It's no longer blocked 😊

**Closed by olafurpg** 2018-08-28 14:48 UTC
Labels: blocked
