### ISSUE TITLE
Missing error message details in CommandLineError

### ISSUE THREAD

**Issue by stewSquared** [scalacenter/scalafix#920] opened 2018-12-10 16:30 UTC
I've run into a `CommandLineError` in some of my subprojects while running `scalafix RemoveUnused`

```
$ ethereum/scalafix RemoveUnused
[info] Running scalafix on 15 Scala sources
error: Unable to load symbol table: error in opening zip file
[error] (ethereum/compile:scalafix) scalafix.sbt.ScalafixFailed: CommandLineError
```

This is versions 0.9.1 on Oracle JDK 8.
Scalafix works as expected on most of my subprojects.

Gitter discussion: https://gitter.im/scalacenter/scalafix?at=5c0e912333d9e11991aec83d

**Comment by stewSquared** [comment] 2018-12-14 13:49
So, while the error message could be better, I did find the cause of failure on my end.
The affected projects had these settings (don't ask me why):
```scala
     unmanagedClasspath in Compile ++= (unmanagedResources in Compile).value,
     unmanagedClasspath in Compile in Test ++= (unmanagedResources in Test).value
```

**Comment by bjaglin** [comment] 2022-03-30 20:49
duplicate of https://github.com/scalacenter/scalafix/issues/962

**Closed by bjaglin** 2022-03-30 20:49 UTC
