### ISSUE TITLE
Load a custom rule with configuration

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#778] opened 2018-07-20 11:35 UTC
If I try to run scalafix testkit on a rule with configuration
```scala
case class MyRule(index: SemanticdbIndex, config: MyRuleConfig) extends SemanticRule(index, "MyRule") {
// ...
  override def init(config: Conf): Configured[Rule] = // ...
  override def fix(ctx: RuleCtx): Patch = // ...
}
```

I get tho following error

```
[info] [E0] Type mismatch;
[info]   found    : String (value: "scala:fix.MyRule")
[info]   expected : scalafix.rule.Rule
[info] [E1] Type mismatch;
[info]   found    : String (value: "scala:fix.MyRule")
[info]   expected : scalafix.rule.Rule
[info] [E2] java.lang.IllegalArgumentException: Unable to load rule fix.MyRule with args scalafix.internal.config.ScalafixMetaconfigReaders$$Lambda$26669/1179995075@13fd7b6d. Tried the following:
[info] java.lang.IllegalArgumentException: No suitable constructor on class fix.MyRule.
[info] Expected : zero argument constructor  or constructor matching arguments List(EagerInMemorySemanticdbIndex(, /home/gui/scala-collection-compat/scalafix/input/target/scala-2.12/classes, database.size=16))
[info] Found    : List(public fix.MyRule(scalafix.util.SemanticdbIndex,fix.MyRuleConfig))
[info]              
[info]  scalafix.internal.util.ClassloadRule.$anonfun$classloadClassRule$6(ClassloadRule.scala:70) 
[info] scala.Option.getOrElse(Option.scala:121) 
[info] scalafix.internal.util.ClassloadRule.$anonfun$classloadClassRule$1(ClassloadRule.scala:63) 
[info] scala.util.Try$.apply(Try.scala:209) 
[info] scalafix.internal.util.ClassloadRule.classloadClassRule(ClassloadRule.scala:55) 
[info] scalafix.internal.util.ClassloadRule.$anonfun$classloadRule$1(ClassloadRule.scala:91) 
[info] scala.util.Success.flatMap(Try.scala:247) 
[info] scalafix.internal.util.ClassloadRule.classloadRule(ClassloadRule.scala:90) 
[info] scalafix.internal.util.ClassloadRule$.apply(ClassloadRule.scala:124) 
[info] scalafix.internal.config.ScalafixMetaconfigReaders$$anonfun$classloadRuleDecoder$1.applyOrElse(ScalafixMetaconfigReaders.scala:154)
[info] java.lang.ClassCastException: fix.MyRule$ is not a subtype of class scalafix.rule.Rule
[info]  scalafix.internal.util.ClassloadRule.$anonfun$classloadClassRule$1(ClassloadRule.scala:81) 
[info] scala.util.Try$.apply(Try.scala:209) 
[info] scalafix.internal.util.ClassloadRule.classloadClassRule(ClassloadRule.scala:55) 
[info] scalafix.internal.util.ClassloadRule.$anonfun$classloadRule$2(ClassloadRule.scala:94) 
[info] scala.util.Success.flatMap(Try.scala:247) 
[info] scalafix.internal.util.ClassloadRule.classloadRule(ClassloadRule.scala:93) 
[info] scalafix.internal.util.ClassloadRule$.apply(ClassloadRule.scala:124) 
[info] scalafix.internal.config.ScalafixMetaconfigReaders$$anonfun$classloadRuleDecoder$1.applyOrElse(ScalafixMetaconfigReaders.scala:154) 
[info] scalafix.internal.config.ScalafixMetaconfigReaders$$anonfun$classloadRuleDecoder$1.applyOrElse(ScalafixMetaconfigReaders.scala:145) 
[info] metaconfig.ConfDecoder$$anon$2.read(ConfDecoder.scala:62)
[info]   at metaconfig.Configured.get(Configured.scala:11)
[info]   at scalafix.testkit.DiffTest$$anonfun$$nestedInanonfun$fromSemanticdbIndex$2$1.applyOrElse(DiffTest.scala:41)
[info]   at scalafix.testkit.DiffTest$$anonfun$$nestedInanonfun$fromSemanticdbIndex$2$1.applyOrElse(DiffTest.scala:33)
[info]   at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:145)
[info]   at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:132)
[info]   at scala.meta.tokens.Tokens.collectFirst(Tokens.scala:28)
[info]   at scalafix.testkit.DiffTest$.$anonfun$fromSemanticdbIndex$2(DiffTest.scala:33)
[info]   at scalafix.testkit.SemanticRuleSuite.$anonfun$runOn$1(SemanticRuleSuite.scala:73)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   ...
```

I found this workaround:

```scala
case class MyRule(index: SemanticdbIndex, config: MyRuleConfig) extends SemanticRule(index, "MyRule") {
  def this(index: SemanticdbIndex) = this(index, MyRuleConfig.default)
}
```

**Comment by olafurpg** [comment] 2018-07-31 12:04
Duplicate of #432

**Closed by olafurpg** 2018-07-31 12:04 UTC
