### ISSUE TITLE
Scalafix plugin uses a lot of memory in the sbt project

### ISSUE THREAD

**Issue by eatkins** [scalacenter/scalafix#1229] opened 2020-08-24 16:55 UTC
I added the scalafix plugin to https://github.com/sbt/sbt and the build became noticeably sluggish. It soon became clear the memory utilization of sbt had skyrocketed after adopting the plugin. I took a heap dump after running scalafix and the heap was dominated by scalafix classes: 
<img width="1007" alt="Screen Shot 2020-08-24 at 9 49 18 AM" src="https://user-images.githubusercontent.com/2658825/91072917-1aee7100-e5ef-11ea-9dcf-cdaeb16b48b7.png">
In particular notice that instance of `ScalafixGlobal` are taking up 725MB and that there are 34 `ScalfixGlobalThreads` running (which I also verified with jstack).

**Comment by japgolly** [comment] 2020-08-25 04:18
Ah.... I've been seeing SBT crash and OOM quite a lot of the last few months. That's around the time that I started using scalafix so I think this explains it.

**Comment by olafurpg** [comment] 2020-08-25 06:49
Thank you for reporting! This looks like a bug indeed. What Scalafix rules did you enable? Can you explain a bit how you invoked Scalafix? For example, are you using scalafix on compile, tab completions, or did Scalafix fail to run?

Looking at the implementation, Scalafix allows rules to clean up acquired resources after normal `scalafix` invocations here

https://github.com/scalacenter/scalafix/blob/b4c8ce50b8b7be7c3ae9f1dae6ac6dbaedefce5c/scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala#L322

The `ExplicitResultTypes` rule should close `ScalafixGlobal` here 

https://github.com/scalacenter/scalafix/blob/b4c8ce50b8b7be7c3ae9f1dae6ac6dbaedefce5c/scalafix-rules/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala#L32-L45

There is a chance that the `afterComplete()` method is not being called in cases like tab completions, but I would be surprised if that was the cause since tab completions should cause `ScalafixGlobal` to get initialized.

A search on GitHub reveals that there are several custom Scalafix rules that are using `ScalafixGlobal` without overriding `afterComplete()` https://github.com/search?q=ScalafixGlobal&type=Code

**Comment by japgolly** [comment] 2020-08-25 07:06
Here's my setup:

`.scalafix.conf`:

```
rules = [
  OrganizeImports,
  RemoveUnused,
]

RemoveUnused {
  imports  = false
  privates = true
  locals   = true
}

OrganizeImports {
  expandRelative                             = true
  groupedImports                             = Merge
  groupExplicitlyImportedImplicitsSeparately = false
  groups                                     = ["*"]
  importSelectorsOrder                       = Ascii
  removeUnused                               = true
}
```

`scalafix.sbt`:

```scala
{
  if (Common.releaseMode)
    Nil
  else
    Seq(
      ThisBuild / scalacOptions += "-Yrangepos",
      ThisBuild / semanticdbEnabled := true,
      ThisBuild / scalafixScalaBinaryVersion := "2.13",
      ThisBuild / semanticdbVersion := "4.3.20",
      ThisBuild / scalafixDependencies ++= Seq(
        "com.github.liancheng" %% "organize-imports" % "0.4.0"
      )
    )
}
```

And I don't have it automatically triggered. I just manually run `scalafixAll` from within SBT. Hope that helps!

**Comment by olafurpg** [comment] 2020-08-25 07:33
Thank you @japgolly ! I am not sure if you are hitting on the exact same issue as @eatkins in this case since neither of those rules depend on `ScalafixGlobal`. It's likely Scalafix has high memory usage even if we fix the issue around leaking `ScalafixGlobal` instances but I think it's best to look at that separately

**Comment by eatkins** [comment] 2020-08-25 15:13
I copied the `.scalafix.conf` from metals and made some minor changes:
```
rules = [
  OrganizeImports,
  ExplicitResultTypes,
  RemoveUnused
]

ExplicitResultTypes.rewriteStructuralTypesToNamedSubclass = false

RemoveUnused.imports = false

OrganizeImports.groupedImports = Keep
OrganizeImports.expandRelative = true
OrganizeImports.removeUnused = true
OrganizeImports.groups = [
  "java."
  "scala."
  "sbt."
  "*"
]
```
I also just ran `scalafixAll` in the sbt root project. Here is a branch of sbt that reproduces the issue: https://github.com/eatkins/sbt/tree/scalafix

**Comment by eed3si9n** [comment] 2020-10-27 21:39
Looking at scalafix-organize-imports, there are a few place that it calls `Try(_)`-wrapped `.info`

https://github.com/liancheng/scalafix-organize-imports/blob/88902608da8c6f1c8e64049599244fb8c1c0ead0/rules/src/main/scala/fix/OrganizeImports.scala#L198-L201

```scala
      case importer @ Importer(_, importees) =>
        importees
          .filter(_.is[Importee.Name])
          .filter(name => name.symbol.infoNoThrow exists (_.isImplicit))
```

The above, for instance, is trying to partition whether the imported name is implicit or not by checking the type (`.info`).
This call would hit the "symbol table" of ScalaMeta (I'm guessing), which then could either call scalap or javap. This is likely an expensive call so the result is cached, but the cache is unbounded - https://github.com/scalameta/scalameta/blob/8382c39e5916f33019ec6919b217a03f55afde68/semanticdb/symtab/src/main/scala/scala/meta/internal/symtab/GlobalSymbolTable.scala#L22

```scala
  private val symbolCache = TrieMap.empty[String, SymbolInformation]
```

Not sure how big this gets but it might be interesting to log the size.

**Comment by mlachkar** [comment] 2020-11-02 14:03
Working in it.

**Comment by mlachkar** [comment] 2020-11-03 22:04
So the main issue is that the code that is responsible for killing the presentation compiler before starting a new thread doesn't kill the presentation compiler as expected. So When calling `afterComplete` that calls `global.askShutdown`, sometimes it kills the PresentationCompiler thread, and sometimes the Metals one.

We see left presentation compiler and Metals presentation compiler threads after running tests inside scalafix. 

![image](https://user-images.githubusercontent.com/7843237/98041802-ceab8280-1e22-11eb-99e4-ab79e94f1fd8.png)

This is the code that is supposed to kill the presentation compiler.
```        
val re = askForResponse(() => throw ShutdownReq)
 re.get
```
We can think that this code requests a Shutdown and wait for it, but actually, the `ShutdownReq` is caught and the presentation compiler is never killed. 
When the compiler pollForWork, this method is called, and the throwable is caught  
``` InterruptReq.scala
  /** To be called from interrupted server to execute demanded task */
  def execute(): Unit = synchronized {
    try {
      result = Some(Left(todo()))
    } catch {
      case t: Throwable => result = Some(Right(t))
// case t: Throwable => result = Some(Right(t)); throw t => this code would solve the issue
    } finally {
      notify()
      for (k <- waiting.reverse) k(result.get)
    }
  }
```

So we can either propose a fix in `InterruptReq.scala` which needs to be fixed in multiple scalaVersions , or use `this.askShutDown` (https://github.com/scalacenter/scalafix/pull/1272), or stop hijacking the presentation compiler thread (https://github.com/scalacenter/scalafix/pull/1273).

**This the state before the fix**
![image](https://user-images.githubusercontent.com/7843237/98044184-c81f0a00-1e26-11eb-95f6-6a5407cbea8f.png)


**After either of the solutions**

![image](https://user-images.githubusercontent.com/7843237/98044224-d66d2600-1e26-11eb-98cb-cf0b856f9d4c.png)

**Comment by eed3si9n** [comment] 2020-11-04 12:10
Nice. Thanks for the investigation and presenting clear evidences of fix!

**Closed** 2020-11-04 16:10 UTC
