### ISSUE TITLE
Scalafix 0.9.26 breaks scalafix-organize-imports unit test

### ISSUE THREAD

**Issue by liancheng** [scalacenter/scalafix#1337] opened 2021-02-28 09:30 UTC
```
###########> Diff       <###########

===========
=> Obtained
===========

package fix

import fix.QuotedIdent.`a.b`.c
import fix.QuotedIdent.`a.b`.{ d }
import fix.QuotedIdent.a.b
import fix.QuotedIdent.macro

object ExpandRelativeQuotedIdent

         
=======
=> Diff
=======
--- obtained
+++ expected
@@ -2,6 +2,6 @@
∙
+import fix.QuotedIdent.`a.b`
+import fix.QuotedIdent.`a.b`.`{ d }`
 import fix.QuotedIdent.`a.b`.c
-import fix.QuotedIdent.`a.b`.{ d }
-import fix.QuotedIdent.a.b
-import fix.QuotedIdent.macro
+import fix.QuotedIdent.`macro`
```
```
[info] - fix/ExpandRelativeQuotedIdent.scala *** FAILED ***
[info]   see above (AbstractSemanticRuleSuite.scala:97)
```

So the identifier `` `{ d }` `` in the input is rewritten into `{ d }` without quotation.

More details can be found in this [build](https://github.com/liancheng/scalafix-organize-imports/pull/158/checks?check_run_id=1995615597) of liancheng/scalafix-organize-imports#158.

I'm not sure whether the problem is from 0.9.25 or 0.9.26, because the [Scala Steward PR](https://github.com/liancheng/scalafix-organize-imports/pull/153) for upgrading Scalafix to 0.9.25 failed and I didn't get enough cycles to investigate.

**Comment by bjaglin** [comment] 2021-02-28 20:20
> I'm not sure whether the problem is from 0.9.25 or 0.9.26, because the [Scala Steward PR](https://github.com/liancheng/scalafix-organize-imports/pull/153) for upgrading Scalafix to 0.9.25 failed and I didn't get enough cycles to investigate.

Looking at https://github.com/liancheng/scalafix-organize-imports/pull/153/checks?check_run_id=1736149686, we can see that the tests pass, but the coverage task fail (as mentioned in https://github.com/liancheng/scalafix-organize-imports/pull/153#issuecomment-786485185), so the problem is related to the 0.9.26 upgrade, and most likely to the scalameta bump. I'll have a look.

**Comment by bjaglin** [comment] 2021-02-28 22:03
Looks like a regression introduced in scalameta 4.4.9 (first present in scalafix 0.9.26) https://github.com/scalameta/scalameta/pull/2260

**Comment by liancheng** [comment] 2021-04-08 18:14
I think we need to bump Scalameta version to 4.4.11 or a higher version, which contains scalameta/scalameta#2260, to resolve this one.

**Comment by bjaglin** [comment] 2021-05-14 23:43
I verified via https://github.com/liancheng/scalafix-organize-imports/pull/179 that this is fixed on main. Keeping open for confirmation until a release is cut out next week.

**Comment by bjaglin** [comment] 2021-05-24 11:48
Confirmed via https://github.com/liancheng/scalafix-organize-imports/pull/181

**Closed by bjaglin** 2021-05-24 11:48 UTC
