### ISSUE TITLE
build crashes if git is not defined or used

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#736] opened 2018-05-24 13:02 UTC
I seem to recall harping on about how depending on jgit and doing git magic inside of scalafix was a mixing of concerns... well it seems to have bitten me today. When creating a new project that is not yet git versioned, I get a crash when starting sbt. Scalafix seems to be the culprit.

Also, I shouldn't need to point out that this will also break under other version control systems, such as p4 which is still **heavily** used by corporates (and I hate it more than you can imagine).

```
[error] Caused by: org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
[error] 	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:152)
[error] 	at scalafix.internal.sbt.JGitCompletion.<init>(JGitCompletions.scala:26)
[error] 	at scalafix.internal.sbt.ScalafixCompletionsComponent.gitDiffParser(ScalafixCompletions.scala:100)
[error] 	at scalafix.internal.sbt.ScalafixCompletionsComponent.parser(ScalafixCompletions.scala:153)
[error] 	at scalafix.internal.sbt.ScalafixCompletionsComponent.parser$(ScalafixCompletions.scala:135)
[error] 	at scalafix.internal.sbt.ScalafixCompletions$.parser(ScalafixCompletions.scala:14)
[error] 	at scalafix.sbt.ScalafixPlugin$.<init>(ScalafixPlugin.scala:175)
[error] 	at scalafix.sbt.ScalafixPlugin$.<clinit>(ScalafixPlugin.scala)
```

**Comment by olafurpg** [comment] 2018-05-24 13:26
Duplicate of #575. @MasseGuillaume has been busy with SCP-16 accessible-scala past weeks so he hasn't been able to work on that ticket yet 😉

**Closed by olafurpg** 2018-05-24 13:26 UTC
