### ISSUE TITLE
NoInfer doesn't seem to work

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#650] opened 2018-03-07 22:26 UTC
I'd have expected this config

```
NoInfer.symbols = [
  "java.io.Serializable"
  "scala.Any"
  "scala.Product"
]
```

to have banned this code

```
      if (true) Option("wibble") else Option(1)
```

but it seems fine with it. It infers `Option[Any]`

**Comment by olafurpg** [comment] 2018-03-07 22:28
Can you include a larger reproduction snippet? If that expression is `val x: Any = if (true) Left else Right` then it's not a violation.

**Comment by fommil** [comment] 2018-03-07 22:29
I minimised it a little further, it's `Option` on both sides and it infers `Option[Any]`.

**Comment by olafurpg** [comment] 2018-03-07 22:34
Standalone ` if (true) Option("wibble") else Option(1)` does not infer `Any`, you need to bind it to a variable without a type annotation in order to trigger the rule. I'm not even sure the following triggers an error

```scala
def foo(x: Option[Any]) = ???
foo(if (true) Option("") else Option(1))
```

Scalafix  reports whatever scalac infers.

**Comment by fommil** [comment] 2018-03-07 22:35
```scala
      val wibble = if (true) Option("wibble") else Option(1)
```

is passing as well.

**Comment by olafurpg** [comment] 2018-03-07 22:36
Cool, that I can work with! 😄

**Comment by fommil** [comment] 2018-03-07 22:36
at a guess, it's forgetting to check the type parameters

**Comment by fommil** [comment] 2018-03-07 22:39
ouch, even this doesn't work

```
      val wibble = if (true) Left("wibble") else Option(1)
```

which should infer `AnyRef with Serializable with Product` if I'm not mistaken.

**Comment by olafurpg** [comment] 2018-03-07 22:50
PS, note NoInfer will be removed soon in favor of `Disable.ifSynthetic`. Not sure how that changes this, just for the record

**Comment by fommil** [comment] 2018-03-07 22:52
I think that's a good move. I am confused by the difference. I guess you're unifying types and symbols in the rules, :100:

**Comment by fommil** [comment] 2018-03-07 22:53
oh, nice, `isSynthetic` catches this. I'm ok to close if that's the path forward? I'll just not use `NoInfer`.

**Comment by olafurpg** [comment] 2018-03-07 22:54
Cool! `NoInfer` should have been removed in @vovapolu 's PR 😄 nothing to see there anymore

**Comment by fommil** [comment] 2018-03-07 22:54
oh noes, it caught the wrong thing!!!

**Comment by olafurpg** [comment] 2018-03-07 23:03
The issue is likely then that we don't check inferred member types, which is a total oversight. It seems to only check inferred terms right now.

**Comment by olafurpg** [comment] 2018-04-23 14:55
I was able to reproduce with this test case

```scala
/* ONLY
rules = Disable
Disable.ifSynthetic = [
  "scala.Any"
]
*/
package test

class DisableIfSynthetic {
  val x =  // assert Disable.Any
    null.asInstanceOf[Any]
}
```

There seems to be a bug in how ContextTraverser uses `allDisabledSymbols` here https://github.com/scalacenter/scalafix/blob/6d48e0c419a63956274cfcc8e9bb23601c75ccfa/scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala#L138

Could you take a look @vovapolu ?

**Comment by olafurpg** [comment] 2018-08-27 16:13
NoInfer has been merged into the `Disable` rule in https://github.com/vovapolu/scaluzzi

**Closed by olafurpg** 2018-08-27 16:13 UTC
Labels: bug
